### PR TITLE
Fixes issues galore

### LINKED ISSUE #140: Issues Gallore
- [x] deployment URLS - `${port}-${deplpymentId}.onpatr.cloud`
 - [x] make the DNS records into a table
 - [x] clicking behind modals should close when it's supposed to, and also stopPropogation
 - [x] Delete Role
 - [x] Edit Role
 - [x] View Permissions for a Role
 - [x] ~~cannot assign more than one role to a user (yes you can)~~
 - [x] See who has been assigned to what role
 - [x] oddly italicised `@` (this is an issue with the font)
          Image
 - [x] bogus DNS records
          Image
 - [x] Runner list has a pointer but clicking on it does nothing, remove the cursorpointer
 - [x] Deployment create still has bad link
 - [ ] Image name shouldn’t be editable. It can’t be edited. There’s no API for it
 - [x] Deployment list table isn't aligned properly
       Image
 - [x] When I select “All deployments” for a role it creates an empty resource list with include instead of exclude

### LINKED ISSUE #143: [BUG] `sessionStorage` not defined for frontend
```
[useFetchUserPermissions] Error fetching user permissions: ReferenceError: sessionStorage is not defined
    at eval (/workspace/frontend/src/hooks/use-fetch/use-user-permissions.tsx:165:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
```

Got this on the terminal of the frontend

### PR DESCRIPTION
**Pull request by rakshith-ravi**
Fix https://github.com/patr-cloud/patr/issues/140
Fixes https://github.com/patr-cloud/patr/issues/143

### CODE REVIEW

File: frontend/src/pages/auth/login.tsx [hunk 1]
```diff
@@ -269,8 +274,21 @@ const Login = () => {
...
 						>
-							Login
+							<Show when={isLoading()} fallback="Login">
+								<div class="flex items-center gap-2">
+									<svg class="animate-spin h-5 w-5" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
+										<circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4" />
+										<path
+											class="opacity-75"
+											fill="currentColor"
+											d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
```
Comment (rakshith-ravi) [inline frontend/src/pages/auth/login.tsx]: SVG?

File: frontend/src/pages/auth/login.tsx [hunk 2]
```diff
@@ -269,8 +274,21 @@ const Login = () => {
 							variant={ButtonVariant.Contained}
 							class="py-4 text-base font-semibold px-xxl flex-end"
 							type="submit"
+							disabled={isLoading()}
 						>
-							Login
+							<Show when={isLoading()} fallback="Login">
```
Comment (rakshith-ravi) [inline frontend/src/pages/auth/login.tsx:279]: When loading, the button should just be yellow
