### PR TITLE
Fix Deployment Dashboard UI, added Route macros for routes

### LINKED ISSUE #45: Wrong alignment of deployment card
Screenshot 2024-09-20 at 5 13 12 AM

Happens with the self-hosted runner on the `feature/self-hosted-frontend` branch

 - [x] Fix overflowing components
 - [x] Fix word wrapping for list item fields
 - [ ] #52

### PR DESCRIPTION
**Pull request by argha-dot**
Fixes #45 
Added app routes for deployment, runner, workspace routes

### CODE REVIEW

File: hosted-frontend/src/routes/mod.rs [hunk 1]
```diff
@@ -1,14 +1,43 @@
...
+
+#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Default)]
+pub struct CommonQueryParams {
+	/// The Page number to fetch
+	#[serde(skip_serializing_if = "Option::is_none")]
+	pub page: Option<u32>,
+	/// The Sorting order of the deployments
+	#[serde(skip_serializing_if = "Option::is_none")]
+	pub order: Option<SortDirection>,
+	/// Filter the deployments by date
```
Comment (rakshith-ravi) [inline hosted-frontend/src/routes/mod.rs]: This has not been fixed yet

**Review by rakshith-ravi — CHANGES_REQUESTED** [review]

**Review by rakshith-ravi — APPROVED** [review]

**Comment by rakshith-ravi** [comment]
Merging this for now. Any updates can be put in a separate PR
